# Generated by Django 4.2.16 on 2024-11-30 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projet_don'),
    ]

    operations = [
        migrations.RenameField(
            model_name='don',
            old_name='adresse',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='don',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='don',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='don',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projet', to='app.projet'),
        ),
    ]
