# Generated by Django 4.2.16 on 2024-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_adresse_don_receiver_don_date_don_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
