# Generated by Django 4.2.16 on 2024-12-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_don_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
